apiVersion: v1
kind: Pod
spec:
  containers:
    - name: nodejs
      image: node:lts-trixie-slim
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: '1Gi'
          cpu: '1000m'
        limits:
          memory: '2Gi'
          cpu: '2000m'
    - name: sonar-scanner-cli
      image: sonarsource/sonar-scanner-cli:5.0.1
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: '500Mi'
          cpu: '500m'
        limits:
          memory: '1Gi'
          cpu: '1000m'
    # - name: kaniko
    #   image: gcr.io/kaniko-project/executor:debug
    #   command:
    #     - sleep
    #   args:
    #     - infinity
    #   volumeMounts:
    #     - name: harbor-credentials
    #       mountPath: /kaniko/.docker
    #     - name: jenkins-artifacts
    #       mountPath: /artifacts
    # - name: alpine-harbor-scanner
    #   image: alpine
    #   command:
    #     - sleep
    #   args:
    #     - infinity
    #   volumeMounts:
    #     - name: jenkins-artifacts
    #       mountPath: /artifacts
    # - name: crane
    #   image: gcr.io/go-containerregistry/crane:debug
    #   command:
    #     - sleep
    #   args:
    #     - infinity
    #   volumeMounts:
    #     - name: harbor-credentials
    #       mountPath: /root/.docker/config.json
    #       subPath: config.json
    #     - name: jenkins-artifacts
    #       mountPath: /artifacts
  # - name: helm
  #   image: alpine/helm:3.14.2
  #   command:
  #   - sleep
  #   args:
  #   - infinity
  #   volumeMounts:
  #     - name: jenkins-artifacts
  #       mountPath: /artifacts
  # volumes:
  #   - name: harbor-credentials
  #     secret:
  #       secretName: harbor-credentials
  #       items:
  #         - key: .dockerconfigjson
  #           path: config.json
  #   - name: jenkins-artifacts
  #     persistentVolumeClaim:
  #       claimName: jenkins-artifacts-pvc
